In [1]:
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..','..')))

In [2]:
from feature_engineering import FeatureExtraction
import pandas as pd

In [3]:
file_path = "../../data/Expenditure-of-local-bodies.xlsx"
if not os.path.exists(file_path):
    print("Dataset not found!")
else:
    print("Good to go!")

Good to go!

In [4]:
feature_extraction = FeatureExtraction(fname=file_path, province_name="Bagmati Province")
budget, expense = feature_extraction.extract_individual()
budget.head()

Original data extracted successfully☺️
DataFrame Renamed successfully☺️
ALL THE OPERSTIONS WERE SUCCESSFUL😊

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
277,274,Jiri Municipality,32.1781,21.796821,0.0,53.974921,5.259159
278,275,Bhimeshwor Municipality,40.456662,53.925065,0.15,94.531727,6.743792
279,276,Kalinchwok Rural Municipality,43.495598,30.00791,0.0,73.503508,8.158327
280,277,Gaurisahnkar Rural Municipality,29.82713,20.8173,0.0,50.64443,4.510428
281,278,Tamakoshi Rural Municipality,44.341532,26.595364,0.0,70.936896,17.064383

In [5]:
df = feature_extraction.open_file()
df = feature_extraction.rename_label(dataframe=df)

In [6]:
df.head(10)

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,23.587589,15.188281,0.0,38.775871,2.881517
5,6,Mauwakhola Rural Municipality,21.46895,14.5531,0.0,36.02205,18.164198,13.060848,0.0,31.225046,4.327077
6,7,Pathibhara Yangwarak Rural Municipality,27.369047,21.029567,0.0,48.398614,23.399494,13.367955,0.0,36.767449,6.686506
7,8,Sidingwa Rural Municipality,30.86315,12.018302,0.0,42.881452,24.468454,9.661338,0.0,34.129792,5.39351
8,9,Sirijangha Rural Municipality,34.966189,16.8545,0.0,51.820689,29.937784,12.554113,0.0,42.491897,5.085653
9,10,Phidim Municipality,80.195151,16.536,0.0,96.731151,63.1087,11.754038,0.0,74.862737,7.680615

In [7]:
df.columns

Index(['SN', 'Local Body', 'Recurrent', 'Capital', 'Financial', 'Total',
       'Recurrent', 'Capital', 'Financial', 'Total', 'Cash Balance'],
      dtype='object')

In [8]:
df['SN'].head()

0    1
1    2
2    3
3    4
4    5
Name: SN, dtype: object

In [9]:
df = feature_extraction.extract_expenditure_frame(df)
df.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,23.587589,15.188281,0.0,38.775871,2.881517

In [10]:
df_filtered = df[df["Local Body"].str.contains(r'(?:Sub-Metropolitan|Metropolitan)$', case=False, na=False)]
df_filtered.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
108,109,Biratnagar Metropolitan,106.329656,86.189002,4.30181,196.820467,46.12698
125,126,Itahari Sub-Metropolitan,83.120802,51.578389,0.0,134.699191,48.036981
126,127,Dharan Sub-Metropolitan,81.431079,49.05564,2.9477,133.43442,29.887517
174,173,Janakpurdham Sub-Metropolitan,85.549529,40.428753,0.0,125.978283,44.862408
245,244,Kalaiya Sub-Metropolitan,65.561599,55.608887,0.0,121.170486,26.22197

In [11]:
df_filtered.shape

(17, 7)

In [12]:
def filter_list(dataframe: pd.DataFrame):
    df = dataframe[dataframe["Local Body"].str.contains(r'?:Sub-Metropolitan|Metropolitan)$', case=False, na=False)]
    return df

### Testing implementation

In [14]:
from feature_engineering import FeatureExtractionUrban

In [15]:
final_df = FeatureExtractionUrban(df=budget).extract_urban_features()
final_df.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
358,355,Bharatpur Metropolitan,197.692678,292.229399,0.0,489.922077,163.427313
365,362,Hetauda Sub-Metropolitan,119.985973,133.746327,0.6,254.3323,105.282164
379,376,Lalitpur Metropolitan,142.927227,273.752645,0.0,416.679872,181.757992
385,382,Kathmandu Metropolitan,546.5301,972.5085,37.1128,1556.1514,983.660309

In [16]:
final_df.size

28

In [17]:
final_df.shape

(4, 7)

In [20]:
final_df = FeatureExtractionUrban(df=df).extract_urban_features()
final_df.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
108,109,Biratnagar Metropolitan,106.329656,86.189002,4.30181,196.820467,46.12698
125,126,Itahari Sub-Metropolitan,83.120802,51.578389,0.0,134.699191,48.036981
126,127,Dharan Sub-Metropolitan,81.431079,49.05564,2.9477,133.43442,29.887517
174,173,Janakpurdham Sub-Metropolitan,85.549529,40.428753,0.0,125.978283,44.862408
245,244,Kalaiya Sub-Metropolitan,65.561599,55.608887,0.0,121.170486,26.22197

In [19]:
final_df.shape

(17, 7)

### working fine